spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/ourcompanylunch
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:
  jpa:
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
  mail:
    host: smtp.gmail.com
    port: 587
    username: hello@gmail.com
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
s3:
  bucket-name:
  diner-max-image-count: 10
cloudfront-url:
common:
  jwt:
    secret:
    expired-in-hour: 1
scheduler:
  clear-verification-code:
    cron: "0 0 3 * * *" # Run every day 03:00 AM
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
management:
  endpoints:
    web:
      exposure:
        include: '*'