spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/companylunchcomment
    driver-class-name: org.mariadb.jdbc.Driver
    username:
    password:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
  jwt:
    secret:
    expired-in-hour: 24
  mail:
    host: smtp.gmail.com
    port: 587
    username: hello@gmail.com
    password:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
s3:
  bucket-name:
  diner-max-image-count: 10

bypass-email-domain-check-for-dev: true # If true, you can receive email with gmail.com, naver.com, ...
